/*
 * ResidentAdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.ResidentAdminRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.WaterQualityMonitoring;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author  Gaurav
 */
public class ResidentAdminWorkAreaJPanel extends javax.swing.JPanel {
      private BufferedImage image;
    JPanel userProcessContainer;
    Enterprise enterprise;
    private Network ntw;
    WaterQualityMonitoring system;
    /** Creates new form AdminWorkAreaJPanel */
    public ResidentAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,Network ntw,WaterQualityMonitoring system) {
        initComponents();
        this.system=system;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ntw = ntw;
        valueLabel.setText(enterprise.getName());
        
        setImg();
        
        
        
        
       // pack();
    }
    
    
    public void setImg(){
    setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 5));
        try
        {
            image = ImageIO.read(new File(getClass().getResource("/userinterface/water-background.jpg").toURI()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
     @Override
    public Dimension getPreferredSize()
    {
        return (new Dimension(300, 300));
    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    
  

    
        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageUserAccount = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Work Area - Resident Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 149, -1, 40));

        manageUserAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageUserAccount.setForeground(new java.awt.Color(0, 0, 153));
        manageUserAccount.setText("Manage Resident User Account");
        manageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountActionPerformed(evt);
            }
        });
        add(manageUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 250, 30));

        manageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(0, 0, 153));
        manageEmployeeJButton.setText("Manage Residents");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 250, 30));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 102));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 360, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WATER QUALITY  MANAGEMENT SYSTEM ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountActionPerformed
        // TODO add your handling code here:
        ManageResidentUserAccountJPanel mruajp = new ManageResidentUserAccountJPanel(userProcessContainer, enterprise,system);
        userProcessContainer.add("ManageUserAccountJPanel", mruajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageResidentJPanel manageResidentEmployeeJPanel = new ManageResidentJPanel(userProcessContainer, (enterprise).getSupportedOrganization(),ntw,system);
        userProcessContainer.add("manageEmployeeResidentJPanel", manageResidentEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageUserAccount;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
