/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FundApprover;


import Business.WorkQueue.AskFunds;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ApproveFundsRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AskFunds request;
    private BufferedImage image;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ApproveFundsRequestJPanel(JPanel userProcessContainer, AskFunds request) {
        initComponents();
      try{  this.userProcessContainer = userProcessContainer;
        this.request = request;
      
        nameLbl.setText(request.getSender().getPerson().getName());
        aloneLbl.setText(String.valueOf(request.getSender().getSeniorPerson().isStayAlone()));
        age.setText(String.valueOf(request.getAge()));
        medCon.setText(request.getCondition());
        resultjTextArea1.setText(request.getComments());
        relation.setText(request.getRelation());
        fund.setText(String.valueOf(request.getAvailableAmount()));
        leg.setText(String.valueOf(request.isLegitimate()));
        setImg();   }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
       }
    
     public void setImg(){
    setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 5));
        try
        {
            image = ImageIO.read(new File(getClass().getResource("/userinterface/elderCare.jpg").toURI()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
     @Override
    public Dimension getPreferredSize()
    {
        return (new Dimension(300, 300));
    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rejectJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultjTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        aloneLbl = new javax.swing.JLabel();
        medCon = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        fund = new javax.swing.JLabel();
        relation = new javax.swing.JLabel();
        approveJButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        leg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rejectJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rejectJButton.setForeground(new java.awt.Color(51, 0, 51));
        rejectJButton.setText("Reject");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });
        add(rejectJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Extra Comments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        resultjTextArea1.setColumns(20);
        resultjTextArea1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        resultjTextArea1.setForeground(new java.awt.Color(0, 51, 204));
        resultjTextArea1.setRows(5);
        resultjTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(resultjTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 480, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Person Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Age");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 50, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Medical Conditions");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Available Funds to Support Their Living Expenses:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Relation With Younger Family Members");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(0, 51, 204));
        nameLbl.setText("jLabel9");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 130, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Staying Alone");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, 20));

        aloneLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aloneLbl.setForeground(new java.awt.Color(0, 51, 204));
        aloneLbl.setText("jLabel11");
        add(aloneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 120, 20));

        medCon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        medCon.setForeground(new java.awt.Color(0, 51, 204));
        medCon.setText("jLabel2");
        add(medCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 130, 20));

        age.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        age.setForeground(new java.awt.Color(0, 51, 204));
        age.setText("jLabel9");
        add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 120, 20));

        fund.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fund.setForeground(new java.awt.Color(0, 51, 204));
        fund.setText("jLabel11");
        add(fund, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 220, 20));

        relation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        relation.setForeground(new java.awt.Color(0, 51, 204));
        relation.setText("jLabel12");
        add(relation, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 220, 20));

        approveJButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        approveJButton1.setForeground(new java.awt.Color(51, 0, 51));
        approveJButton1.setText("Approve");
        approveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButton1ActionPerformed(evt);
            }
        });
        add(approveJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Legitimate Requestor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 140, 20));

        leg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        leg.setForeground(new java.awt.Color(0, 51, 204));
        leg.setText("jLabel9");
        add(leg, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 120, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 153));
        jLabel9.setText("Approve Funds");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Smart Health Care System");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FundApproverWorkAreaJPanel1 ses = (FundApproverWorkAreaJPanel1) component;
        ses.populateTable();
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        try{request.setStatus("Completed");
        request.setApproved(false);
        request.setResolveDate(new Date());
        JOptionPane.showMessageDialog(this, "The request is rejected");
           }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
    }//GEN-LAST:event_rejectJButtonActionPerformed

    private void approveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButton1ActionPerformed
       try{ request.setStatus("Completed");
        request.setApproved(true);
        request.setResolveDate(new Date());
        JOptionPane.showMessageDialog(this, "The request is approved");  // TODO add your handling code here:
           }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
    }//GEN-LAST:event_approveJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel aloneLbl;
    private javax.swing.JButton approveJButton1;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel fund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leg;
    private javax.swing.JLabel medCon;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton rejectJButton;
    private javax.swing.JLabel relation;
    private javax.swing.JTextArea resultjTextArea1;
    // End of variables declaration//GEN-END:variables
}
