/*
 * ResidentWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.ResidentRole;


import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author  Gaurav
 */
public class ResidentWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;
    private BufferedImage image;
    private Network ntw;
    /** Creates new form AdminWorkAreaJPanel */
    public ResidentWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount account,Network ntw) {
        initComponents();
        this.setSize(650, 530);
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account=account;
        this.ntw = ntw;
        valueLabel.setText(enterprise.getName());
        setImg();   
    }
    
      public void setImg(){
    setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 5));
        try
        {
            image = ImageIO.read(new File(getClass().getResource("/userinterface/water-background.jpg").toURI()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
     @Override
    public Dimension getPreferredSize()
    {
        return (new Dimension(300, 300));
    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageFamilyMembers = new javax.swing.JButton();
        createVitalSigns = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageVitalSigns1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Work Area - Resident Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        manageFamilyMembers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageFamilyMembers.setForeground(new java.awt.Color(0, 0, 153));
        manageFamilyMembers.setText("Manage Family Members");
        manageFamilyMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFamilyMembersActionPerformed(evt);
            }
        });
        add(manageFamilyMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 190, 30));

        createVitalSigns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createVitalSigns.setForeground(new java.awt.Color(0, 0, 153));
        createVitalSigns.setText("Enter Vital Signs");
        createVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVitalSignsActionPerformed(evt);
            }
        });
        add(createVitalSigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 190, 30));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 102));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 360, 30));

        manageVitalSigns1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageVitalSigns1.setForeground(new java.awt.Color(0, 0, 153));
        manageVitalSigns1.setText("Manage Vital Signs");
        manageVitalSigns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVitalSigns1ActionPerformed(evt);
            }
        });
        add(manageVitalSigns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 190, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WATER QUALITY  MANAGEMENT SYSTEM ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("WATER QUALITY  MANAGEMENT SYSTEM ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void manageFamilyMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFamilyMembersActionPerformed
        // TODO add your handling code her
        
        ManageFamilyMembersJPanel manageFamilyMembersJPanel = new ManageFamilyMembersJPanel(userProcessContainer,account.getResidents());
        userProcessContainer.add("ManageVitalSignsJPanel", manageFamilyMembersJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFamilyMembersActionPerformed

    private void createVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVitalSignsActionPerformed

        CreateVitalSignJPanel createVitalSignJPanel = new CreateVitalSignJPanel(userProcessContainer,account.getResidents(),ntw);
        userProcessContainer.add("ManageResidentJPanel", createVitalSignJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_createVitalSignsActionPerformed

    private void manageVitalSigns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVitalSigns1ActionPerformed
        // TODO add your handling code here:
        ManageVitalSignsJPanel manageVitalSignsJPanel = new ManageVitalSignsJPanel(userProcessContainer,account.getResidents(),ntw);
        userProcessContainer.add("ManageVitalSignsJPanel", manageVitalSignsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageVitalSigns1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createVitalSigns;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton manageFamilyMembers;
    private javax.swing.JButton manageVitalSigns1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
