/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SurveyorRole;


import Business.Utils.MyIntegerVerifier;
import Business.WorkQueue.AskFunds;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ProcessFundsRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    AskFunds request;
    private BufferedImage image;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessFundsRequestJPanel(JPanel userProcessContainer, AskFunds request) {
        initComponents();
     try{   this.userProcessContainer = userProcessContainer;
        this.request = request;
        populateComboBox();
        nameLbl.setText(request.getSender().getPerson().getName());
        aloneLbl.setText(String.valueOf(request.getSender().getSeniorPerson().isStayAlone()));
        setImg();
        MyIntegerVerifier ms = new MyIntegerVerifier();
        amountTxt.setInputVerifier(ms);
           }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
    }
    public void populateComboBox(){
        medConditionjComboBox1.removeAllItems();
        medConditionjComboBox1.addItem("Unheathy");
        medConditionjComboBox1.addItem("Critical Condition");
        medConditionjComboBox1.addItem("Normal");
                      
        relationjComboBox.removeAllItems();
        relationjComboBox.addItem("Heathy");
        relationjComboBox.addItem("Ignorant");
        relationjComboBox.addItem("Distant but Healthy");
                
    }
    
     public void setImg(){
    setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 5));
        try
        {
            image = ImageIO.read(new File(getClass().getResource("/userinterface/elderCare.jpg").toURI()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
     @Override
    public Dimension getPreferredSize()
    {
        return (new Dimension(300, 300));
    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultjTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        aloneLbl = new javax.swing.JLabel();
        agejSpinner = new javax.swing.JSpinner();
        medConditionjComboBox1 = new javax.swing.JComboBox();
        amountTxt = new javax.swing.JTextField();
        relationjComboBox = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(51, 0, 51));
        submitJButton.setText("Submit Response");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Extra Comments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 204));

        resultjTextArea1.setColumns(20);
        resultjTextArea1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        resultjTextArea1.setForeground(new java.awt.Color(0, 51, 204));
        resultjTextArea1.setRows(5);
        jScrollPane1.setViewportView(resultjTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 550, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Record Survey Details");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Person Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Age");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 50, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Medical Conditions");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Available Funds to Support Their Living Expenses:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Relation With Younger Family Members");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(0, 51, 204));
        nameLbl.setText("jLabel9");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 170, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Staying Alone");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, 20));

        aloneLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aloneLbl.setForeground(new java.awt.Color(0, 51, 204));
        aloneLbl.setText("jLabel11");
        add(aloneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 100, 20));

        agejSpinner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(agejSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 70, -1));

        medConditionjComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        medConditionjComboBox1.setForeground(new java.awt.Color(0, 51, 204));
        medConditionjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(medConditionjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 170, 30));

        amountTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amountTxt.setForeground(new java.awt.Color(0, 51, 204));
        add(amountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 180, 30));

        relationjComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        relationjComboBox.setForeground(new java.awt.Color(0, 51, 204));
        relationjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(relationjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 180, 30));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 51, 204));
        jCheckBox1.setText("Legitimate Requestor");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Smart Health Care System");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
          Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SurveyorWorkAreaJPanel1 wes = (SurveyorWorkAreaJPanel1) component;
        wes.populateTable();
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
       try{
        String relation =(String)relationjComboBox.getSelectedItem();
        String condition = (String)medConditionjComboBox1.getSelectedItem();
        int age = (int)agejSpinner.getValue();
        String comment = resultjTextArea1.getText();
        boolean leg = jCheckBox1.isSelected();
        
        if ((relation.equals("")||condition.equals("")||age==0||comment.equals("")||amountTxt.getText().equals("")))
        {
          JOptionPane.showMessageDialog(this, "Please fill all the above paramenters");
            return;
        }
        double availamount = Double.parseDouble(amountTxt.getText());
      
        request.setComments(comment);
        request.setSurveyDate(new Date());
       
        request.setSurveyDone(true);
        request.setRelation(relation);
        request.setCondition(condition);
        request.setAge(age);
        request.setAvailableAmount(availamount);
        request.setLegitimate(leg);
        JOptionPane.showMessageDialog(this, "The survey is submitted");
           }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
    }//GEN-LAST:event_submitJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner agejSpinner;
    private javax.swing.JLabel aloneLbl;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox medConditionjComboBox1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JComboBox relationjComboBox;
    private javax.swing.JTextArea resultjTextArea1;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
