/*
 * SurveyorWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.WaterQualityManagement;


import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SurveyorOrganization;
import Business.UserAccount.UserAccount;
import Business.WaterQualityMonitoring;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  Gaurav
 */
public class SurveyorWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
     UserAccount account;
     Organization organization;
    Enterprise enterprise;
    Network ntwk;
    WaterQualityMonitoring business;
    private BufferedImage image;
    /** Creates new form AdminWorkAreaJPanel */
    public SurveyorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Organization organization,Enterprise enterprise,WaterQualityMonitoring business,Network ntwk) {
        initComponents();
        this.setSize(650, 530);
        this.userProcessContainer = userProcessContainer;
        this.account=account;
        this.enterprise = enterprise;
        this.account=account;
        this.ntwk=ntwk;
        this.organization= (SurveyorOrganization)organization;
        this.business=business;
        valueLabel.setText(enterprise.getName());
        setImg();
        
    }
    
        public void setImg(){
    setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 5));
        try
        {
            image = ImageIO.read(new File(getClass().getResource("/userinterface/water-background.jpg").toURI()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
     @Override
    public Dimension getPreferredSize()
    {
        return (new Dimension(300, 300));
    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT  modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EnterSurveyDetails = new javax.swing.JButton();
        enterReadings = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        viewReadings = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Work Area - Surveyor Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        EnterSurveyDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterSurveyDetails.setForeground(new java.awt.Color(0, 0, 153));
        EnterSurveyDetails.setText("View Work Requests");
        EnterSurveyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterSurveyDetailsActionPerformed(evt);
            }
        });
        add(EnterSurveyDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 220, 30));

        enterReadings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enterReadings.setForeground(new java.awt.Color(0, 0, 153));
        enterReadings.setText("Enter Water Quality Reading");
        enterReadings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterReadingsActionPerformed(evt);
            }
        });
        add(enterReadings, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 220, 30));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 102));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 380, 30));

        viewReadings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewReadings.setForeground(new java.awt.Color(0, 0, 153));
        viewReadings.setText("View Readings");
        viewReadings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReadingsActionPerformed(evt);
            }
        });
        add(viewReadings, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 220, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WATER QUALITY  MANAGEMENT SYSTEM ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void EnterSurveyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterSurveyDetailsActionPerformed
        // TODO add your handling code her
        if (organization.getWorkQueue().getWorkRequestList().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "There is no request that needs to be processed", "SUCCESS", JOptionPane.PLAIN_MESSAGE);
            return;
        }else{
        ViewSurveyorWorkRequestJPanel viewSurveyorWorkRequestJPanel = new ViewSurveyorWorkRequestJPanel(userProcessContainer,account,organization,enterprise,business,ntwk);
        userProcessContainer.add("ViewSurveyorWorkRequestJPanel", viewSurveyorWorkRequestJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_EnterSurveyDetailsActionPerformed

    private void enterReadingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterReadingsActionPerformed

        CreateReadingsJPanel createReadingsJPanel = new CreateReadingsJPanel(userProcessContainer,ntwk);
        userProcessContainer.add("CreateReadingsJPanel", createReadingsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_enterReadingsActionPerformed

    private void viewReadingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReadingsActionPerformed
        // TODO add your handling code here:
        ViewReadingsJPanel viewReadingsJPanel = new ViewReadingsJPanel(userProcessContainer,ntwk,account);
        userProcessContainer.add("ViewReadingsJPanel", viewReadingsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReadingsActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterSurveyDetails;
    private javax.swing.JButton enterReadings;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewReadings;
    // End of variables declaration//GEN-END:variables
    
}
