/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.Enterprise.CityHealthCareDepartmentEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HigherAuthorityOrganization;
import Business.Organization.Organization;
import Business.USA_Smart_HealthCare;
import Business.UserAccount.UserAccount;
import Business.Utils.MyStringVerifier;
import Business.WorkQueue.AskFunds;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Apoorva
 */
public class AskFundsJPanel1 extends javax.swing.JPanel {

    
  
        private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private USA_Smart_HealthCare business;
    private Network network;
    private BufferedImage image;
   
    /**
     * Creates new form askAssistanceJPanel
     */
    public AskFundsJPanel1(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, USA_Smart_HealthCare business,
            Network network) {
        initComponents();
       try{
           this.userProcessContainer= userProcessContainer;
       
        this.account = account;
        this.organization = organization;
        this.enterprise= enterprise;
        this.business= business;
        this.network = network;
        populateComboBox();
        setImg();
        int count =0;
        AskFunds req = null;
        for(WorkRequest r:  account.getWorkQueue().getWorkRequestList())
        {
        if(r instanceof AskFunds){
            if(!r.getStatus().equals("Completed")){
                count = 1;
            }
             if(r.getStatus().equals("Completed")){
                req = (AskFunds)r;
            }
        }
        
        }
        if(count>0){
        JOptionPane.showMessageDialog(this, "One Fund Request is already sent.Please Wait for its Result");
        }
       if(req!=null){ 
        jLabel4.setText("Important Message");
        
        if(req.isApproved()){
        jLabel3.setText("<html>Your request of Funds <br>is Approved with sectioned <br>amount of $ "+req.getAmount()+"</html>");}
        else {
        jLabel3.setText("<html>Your request of Funds<br> is Rejected</html>");}
       }
       
          }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
       
    }
    
     public void setImg(){
    setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 5));
        try
        {
            image = ImageIO.read(new File(getClass().getResource("/userinterface/elderCare.jpg").toURI()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
     @Override
    public Dimension getPreferredSize()
    {
        return (new Dimension(300, 300));
    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
     public void populateComboBox(){
        reasonjComboBox1.removeAllItems();
        reasonjComboBox1.addItem("Medical Bills");
        reasonjComboBox1.addItem("Accidental Issues");
        reasonjComboBox1.addItem("Living Expenses");
                      
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        assisHelpJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        msgjTextField = new javax.swing.JTextField();
        reasonjComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Welcome to Speed Help");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        assisHelpJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        assisHelpJButton.setForeground(new java.awt.Color(51, 0, 51));
        assisHelpJButton.setText("Request Funds");
        assisHelpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assisHelpJButtonActionPerformed(evt);
            }
        });
        add(assisHelpJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("We are here to serve you");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Ask Us the Funds You Need!!!");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Estimated Money Required");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Reason for Funds Requirements");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Message");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        msgjTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        msgjTextField.setForeground(new java.awt.Color(0, 51, 204));
        msgjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgjTextFieldActionPerformed(evt);
            }
        });
        add(msgjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 431, 160, 30));

        reasonjComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reasonjComboBox1.setForeground(new java.awt.Color(0, 51, 204));
        reasonjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(reasonjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 160, 30));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 312, 97, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 174, 266));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 193, 34));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Smart Health Care System");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void assisHelpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assisHelpJButtonActionPerformed
         try{
 
        String selectedRow = (String) reasonjComboBox1.getSelectedItem();
        
                if (selectedRow.equals("")||jSpinner1.getValue().equals("")||msgjTextField.getText().equals("") ){
                        
                        JOptionPane.showMessageDialog(this, "Please select a reason, fill an amount of donation required and enter a message");
                   return; 
                }
                else{
        
        MyStringVerifier myStringVerifier= new MyStringVerifier();
        msgjTextField.setInputVerifier(myStringVerifier); 
        
        
       
        AskFunds request = new AskFunds();
        request.setMessage(msgjTextField.getText());
        request.setReason(selectedRow);
        request.setAmount((Integer)(jSpinner1.getValue()));
        request.setSender(account);
        request.setStatus("Sent");
        Organization org = null;
        //  System.out.println(" network "+network);
        for (Enterprise enterp: network.getEnterpriseDirectory().getEnterpriseList() ){
            if(enterp instanceof CityHealthCareDepartmentEnterprise){
            for (Organization organization : enterp.getOrganizationDirectory().getOrganizationList()){

                //   System.out.println(" organization "+organization);
                if (organization instanceof HigherAuthorityOrganization){
                    org = organization;
                    // System.out.println("checking isntance");
                    break;
                }
            }}}
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(request);
                account.getWorkQueue().getWorkRequestList().add(request);
                  JOptionPane.showMessageDialog(this, "<html>Your request for funds has been sent to Health Department of City.<br>An Authorized person will make a survey for legitimate Requestor to process your request</html>");
            }}
                   }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
    }//GEN-LAST:event_assisHelpJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkArea pwe = (PatientWorkArea) component;
//        pwe.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void msgjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assisHelpJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField msgjTextField;
    private javax.swing.JComboBox reasonjComboBox1;
    // End of variables declaration//GEN-END:variables
}
