/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AssistantOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.SeniorPerson.SeniorPerson;
import Business.USA_Smart_HealthCare;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Date;
import java.util.Properties;
import javax.imageio.ImageIO;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Apoorva
 */
public class PatientWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private USA_Smart_HealthCare business;
    private Network network;
    private BufferedImage image;
    /**
     * Creates new form PatientWorkArea
     */
    public PatientWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, USA_Smart_HealthCare business,
            Network network) {
        initComponents();
       try{ this.userProcessContainer= userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise= enterprise;
        this.business= business;
        this.network = network;
        jLabel5.setText(account.getPerson().getName());
        setImg();   }
        catch(Exception x)
        { JOptionPane.showMessageDialog(this, "There is some problem please try again later");
        } 
    }
        
     public void setImg(){
    setOpaque(true);
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 5));
        try
        {
            image = ImageIO.read(new File(getClass().getResource("/userinterface/elderCare.jpg").toURI()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
    
    
     @Override
    public Dimension getPreferredSize()
    {
        return (new Dimension(300, 300));
    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adviceJButton = new javax.swing.JButton();
        EmergencyHelpJButton = new javax.swing.JButton();
        manageAppJButton = new javax.swing.JButton();
        orderMedjButton1 = new javax.swing.JButton();
        monitorHealthjButton = new javax.swing.JButton();
        schedulejButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addVitalSignjButton = new javax.swing.JButton();
        viewPresjButton = new javax.swing.JButton();
        fundjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 51, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Welcome to Speed Help");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        adviceJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adviceJButton.setForeground(new java.awt.Color(51, 0, 51));
        adviceJButton.setText("Expert Advice 27 by 7");
        adviceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adviceJButtonActionPerformed(evt);
            }
        });
        add(adviceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 230, -1));

        EmergencyHelpJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EmergencyHelpJButton.setForeground(new java.awt.Color(51, 0, 51));
        EmergencyHelpJButton.setText("Emergency Help!!!");
        EmergencyHelpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyHelpJButtonActionPerformed(evt);
            }
        });
        add(EmergencyHelpJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 230, -1));

        manageAppJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageAppJButton.setForeground(new java.awt.Color(51, 0, 51));
        manageAppJButton.setText("Manage Doctor's Appointment");
        manageAppJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAppJButtonActionPerformed(evt);
            }
        });
        add(manageAppJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 230, -1));

        orderMedjButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderMedjButton1.setForeground(new java.awt.Color(51, 0, 51));
        orderMedjButton1.setText("View/Order Medicine");
        orderMedjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderMedjButton1ActionPerformed(evt);
            }
        });
        add(orderMedjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 230, -1));

        monitorHealthjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        monitorHealthjButton.setForeground(new java.awt.Color(51, 0, 51));
        monitorHealthjButton.setText("Monitor Own Health");
        monitorHealthjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorHealthjButtonActionPerformed(evt);
            }
        });
        add(monitorHealthjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 190, -1));

        schedulejButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        schedulejButton.setForeground(new java.awt.Color(51, 0, 51));
        schedulejButton.setText("Upcoming Schedules");
        schedulejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedulejButtonActionPerformed(evt);
            }
        });
        add(schedulejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("We are here to serve you");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        addVitalSignjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addVitalSignjButton.setForeground(new java.awt.Color(51, 0, 51));
        addVitalSignjButton.setText("Record Vital Signs");
        addVitalSignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalSignjButtonActionPerformed(evt);
            }
        });
        add(addVitalSignjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 190, -1));

        viewPresjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewPresjButton.setForeground(new java.awt.Color(51, 0, 51));
        viewPresjButton.setText("View Prescriptions");
        viewPresjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPresjButtonActionPerformed(evt);
            }
        });
        add(viewPresjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 230, -1));

        fundjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fundjButton.setForeground(new java.awt.Color(51, 0, 51));
        fundjButton.setText("Short of Funds...Ask Us");
        fundjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundjButtonActionPerformed(evt);
            }
        });
        add(fundjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 110, 30));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Smart Health Care System");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void adviceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adviceJButtonActionPerformed
        ViewPreviousAssisJpanel viewPreviousAssisJpanel = new ViewPreviousAssisJpanel(userProcessContainer, account,  organization, enterprise, business,network);
        userProcessContainer.add("viewPreviousAssisJpanel", viewPreviousAssisJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
        
    }//GEN-LAST:event_adviceJButtonActionPerformed

    private void EmergencyHelpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyHelpJButtonActionPerformed
        
       
        EmergencyRequest request = new EmergencyRequest();
        request.setEmergency("Urgent Help");
        request.setLocation("my fall location goes here");//has to updated from location coordinates
        request.setSender(account);
        request.setStatus("Sent");
        System.out.println("in help button");
        
        Organization org = null;
         System.out.println(" network "+network);
         for (Enterprise enterp: network.getEnterpriseDirectory().getEnterpriseList() ){
        for (Organization organization : enterp.getOrganizationDirectory().getOrganizationList()){
           
            System.out.println(" organization "+organization);
            if (organization instanceof AssistantOrganization){
                org = organization;
                System.out.println("checking isntance");
                break;
            }
        }}
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(this,"A person will immediately come to help you at your location");
        }
        
         sendMail(account.getSeniorPerson());                                             
    

    }//GEN-LAST:event_EmergencyHelpJButtonActionPerformed

    private void manageAppJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAppJButtonActionPerformed
ManageAppointmentJPanel manageAppointmentJPanel = new ManageAppointmentJPanel(userProcessContainer, account, organization, enterprise, business, network);
        userProcessContainer.add("manageAppointmentJPanel", manageAppointmentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);    
        
    }//GEN-LAST:event_manageAppJButtonActionPerformed

    private void viewPresjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPresjButtonActionPerformed
          ViewPresJPanel1 viewPresJPanel1 = new ViewPresJPanel1(userProcessContainer, account,  enterprise, business, network);
        userProcessContainer.add("ViewPresJPanel1", viewPresJPanel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
    }//GEN-LAST:event_viewPresjButtonActionPerformed

    private void addVitalSignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalSignjButtonActionPerformed
        RecordVitalSigns recordVitalSigns = new RecordVitalSigns(userProcessContainer, account,business,network);
        userProcessContainer.add("recordVitalSigns", recordVitalSigns);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_addVitalSignjButtonActionPerformed

    private void schedulejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedulejButtonActionPerformed
         ViewScheduleJpanel viewScheduleJpanel = new ViewScheduleJpanel(userProcessContainer, account,  enterprise, business, network);
        userProcessContainer.add("viewScheduleJpanel", viewScheduleJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
   // TODO add your handling code here:
    }//GEN-LAST:event_schedulejButtonActionPerformed

    private void orderMedjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderMedjButton1ActionPerformed
      ViewOrderMedJPanel viewOrderMedJPanel = new ViewOrderMedJPanel(userProcessContainer, account, organization, enterprise, business, network);
        userProcessContainer.add("ViewOrderMedJPanel", viewOrderMedJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);     // TODO add your handling code here:
    }//GEN-LAST:event_orderMedjButton1ActionPerformed

    private void fundjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundjButtonActionPerformed
  AskFundsJPanel1 askFundsJPanel1 = new AskFundsJPanel1(userProcessContainer, account, organization, enterprise, business, network);
        userProcessContainer.add("AskFundsJPanel1", askFundsJPanel1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);           // TODO add your handling code here:
    }//GEN-LAST:event_fundjButtonActionPerformed

    private void monitorHealthjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorHealthjButtonActionPerformed
ViewHealthRecordsJpanel   viewHealthRecordsJpanel = new ViewHealthRecordsJpanel(userProcessContainer, account, organization, enterprise, business, network);
        userProcessContainer.add("ViewHealthRecordsJpanel", viewHealthRecordsJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_monitorHealthjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmergencyHelpJButton;
    private javax.swing.JButton addVitalSignjButton;
    private javax.swing.JButton adviceJButton;
    private javax.swing.JButton fundjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton manageAppJButton;
    private javax.swing.JButton monitorHealthjButton;
    private javax.swing.JButton orderMedjButton1;
    private javax.swing.JButton schedulejButton;
    private javax.swing.JButton viewPresjButton;
    // End of variables declaration//GEN-END:variables


public void sendMail(SeniorPerson p){
    final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
  // Get a Properties object
     Properties props = System.getProperties();
     props.setProperty("mail.smtp.host", "smtp.gmail.com");
     props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
     props.setProperty("mail.smtp.socketFactory.fallback", "false");
     props.setProperty("mail.smtp.port", "465");
     props.setProperty("mail.smtp.socketFactory.port", "465");
     props.put("mail.smtp.auth", "true");
     props.put("mail.debug", "true");
     props.put("mail.store.protocol", "pop3");
     props.put("mail.transport.protocol", "smtp");
      final String username = "sweetpooh29@gmail.com";//
     final String password = "apoorva1990";
 try{
     Session session = Session.getDefaultInstance(props, 
                          new Authenticator(){
                             protected PasswordAuthentication getPasswordAuthentication() {
                                return new PasswordAuthentication(username, password);
                             }});
     
 try{
     for(Person caretakers:p.getCareTakers())
    {
        try{
    // -- Create a new message --
     Message msg = new MimeMessage(session);

  // -- Set the FROM and TO fields --
     msg.setFrom(new InternetAddress(username));
     msg.setRecipients(Message.RecipientType.TO, 
                      InternetAddress.parse(caretakers.getEmailAddress(),false));
        System.out.println("the mail address "+caretakers.getEmailAddress());
     msg.setSubject("Emergency Help Needed!!!");
     msg.setText("I had a severe fall... Please Help!!!");
     msg.setSentDate(new Date());
     Transport.send(msg);
    // System.out.println("Message sent.");
    }  
        
        catch (MessagingException e){ 
  }
    
    }
 }
      catch (NullPointerException e)
      { 
      JOptionPane.showMessageDialog(this, "The email address of care takers not correct");
      }
 
  
}

catch (Exception e){ 
  JOptionPane.showMessageDialog(this, "Email Address is invalid");
  }

}




}
